// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ZXrM9VwOaFy_1w_mWZK5GNyXv019PGA',
    appId: '1:432547762753:android:545c0bcd555f43b482acc0',
    messagingSenderId: '432547762753',
    projectId: 'realtimenotesappdata',
    databaseURL: 'https://realtimenotesappdata-default-rtdb.firebaseio.com',
    storageBucket: 'realtimenotesappdata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5m0Uje8ACIVSisKMgKLacvxZbfu4OO8A',
    appId: '1:432547762753:ios:5d3c41156e8fa82f82acc0',
    messagingSenderId: '432547762753',
    projectId: 'realtimenotesappdata',
    databaseURL: 'https://realtimenotesappdata-default-rtdb.firebaseio.com',
    storageBucket: 'realtimenotesappdata.firebasestorage.app',
    androidClientId: '432547762753-0q6ll0kg482di2lscs0qbvnqe8165eh2.apps.googleusercontent.com',
    iosClientId: '432547762753-kb905sf242imu56kvje4iib2d2ouh261.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5m0Uje8ACIVSisKMgKLacvxZbfu4OO8A',
    appId: '1:432547762753:ios:5d3c41156e8fa82f82acc0',
    messagingSenderId: '432547762753',
    projectId: 'realtimenotesappdata',
    databaseURL: 'https://realtimenotesappdata-default-rtdb.firebaseio.com',
    storageBucket: 'realtimenotesappdata.firebasestorage.app',
    androidClientId: '432547762753-0q6ll0kg482di2lscs0qbvnqe8165eh2.apps.googleusercontent.com',
    iosClientId: '432547762753-kb905sf242imu56kvje4iib2d2ouh261.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

}